//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQSP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int Id_mensaje { get; set; }
        public int Codigo_mensaje { get; set; }
        public string Tipo_mensaje { get; set; }
        public string Cuerpo_mensaje { get; set; }
        public int FKEstadoMensaje { get; set; }
    
        public virtual Estados Estados { get; set; }
    }
}
