//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiQSP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUsuario { get; set; }
        public string CorreoUsuario { get; set; }
        public byte[] ContraseniaUsuario { get; set; }
        public string NombresUsuario { get; set; }
        public string ApellidosUsuaio { get; set; }
        public string TelefonoUsuario { get; set; }
        public string ImagenUsuario { get; set; }
        public int FKEstadoUsuario { get; set; }
        public int FKRolUsuario { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
